FROM quay.io/jupyter/base-notebook:ubuntu-22.04
# based on https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html
# Ubuntu-20.04 is LTS version, see https://endoflife.date/ubuntu
ENV GRANT_SUDO=yes
# disable humbug reporting
# -- BUGGER_OFF for https://bugout.dev
# -- DO_NOT_TRACK for tools compliant with https://consoledonottrack.com
ENV BUGGER_OFF=true
ENV DO_NOT_TRACK=1
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=true
# install additional software
# -- switching to root to avoid having to sudo on every command
USER root
RUN apt-get update -y && \
    apt-get install -y --fix-missing python3-dev default-libmysqlclient-dev build-essential  && \
    apt-get install -y procps htop curl git nano zip && \
    apt-get clean
# enable mssql server support
# adopted from landingpage/getsqlserver.sh
ENV ACCEPT_EULA=Y
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list -o /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && apt upgrade -y && \
    apt-get install -y msodbcsql18 msodbcsql17 unixodbc-dev nano && \
    apt-get clean
# -- set the user back to original setting so $NB_USER is permissioned
# https://stackoverflow.com/a/44683248/890242
USER $NB_USER
RUN fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"




