# this builds the local development image
# uses tips from https://jcrist.github.io/conda-docker-tips.html
FROM ubuntu:18.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=true

COPY ./scripts/updatechromedriver.sh ./scripts/

# https://jpmelos.com/articles/how-use-chrome-selenium-inside-docker-container-running-python/
RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git && \
    apt-get install -y build-essential psmisc libcurl3 libnss3 zip unzip && \
    apt-get install -y default-libmysqlclient-dev gcc procps nano htop curl && \
    update-ca-certificates --fresh && \
    ./scripts/updatechromedriver.sh

# optional install of texlive
# RUN apt-get update --fix-missing && \
#     apt-get install -y texlive-xetex &&
#     rm -rf /var/cache/apt && \
#     rm -rf /var/lib/apt/lists/*  && \
#     apt-get clean

# https://stackoverflow.com/a/44683248/890242
ARG UNAME=omegadev
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
USER $UNAME




