# jupyter stacks data science (including R)
# 3.14 does not exist yet
# [jdsn314]
# image=quay.io/jupyter/datascience-notebook:python-3.14
# tests=omegaml/tests
# extras=all,dev,test

[jdsn313]
image=quay.io/jupyter/datascience-notebook:python-3.13
tests=omegaml/tests
extras=all,dev,test

[jdsn312]
image=quay.io/jupyter/datascience-notebook:python-3.12
tests=omegaml/tests
extras=all,dev,test

[jdsn311]
image=quay.io/jupyter/datascience-notebook:python-3.11
tests=omegaml/tests
extras=all,dev,test
