worker: celery worker --app omegaml.celeryapp -E --loglevel=DEBUG --max-tasks-per-child 1
scheduler:  celery beat --app omegaml.celeryapp --loglevel=debug
notebook: jupyter notebook --allow-root --ip 0.0.0.0 --no-browser $JUPYTER_PARAM --port $JUPYTER_PORT
restapi: python -m omegaml.restapi
