#!/bin/bash

function podssh() {
  pod=`kubectl get pods -o name | grep $1 | cut -d / -f 2 | head -n1`
  shift 1
  cmd=${@:-bash}
  kubectl exec -it $pod -- $cmd
}

function countdown() {
    count=0
    sleep=$1
    while [ $count -lt $1 ]; do
        echo -ne "another $((sleep - count)) seconds...\r"
        sleep 1
        count=$((count +1))
    done
}

function compose_exec() {
  # Like `docker-compose exec` but forwarding stdin to the container
  # See https://github.com/docker/compose/issues/3352
  # https://stackoverflow.com/a/47591157/890242
  local service="$1"; shift
  docker exec -i $(docker-compose ps -q $service) $@
}

function activate_conda() {
    source ~/miniforge3/etc/profile.d/conda.sh || source /opt/conda/etc/profile.d/conda.sh
    cur_env=`conda info | grep "active environment" | cut -d ":" -f 2 | xargs`
    if [ $cur_env == "None" ]; then
       echo "conda setting up base env"
       cur_env=base
       echo "conda activate base" >> ~/.bashrc
    fi
    echo "activating conda env $cur_env"
    conda activate $cur_env
}
